// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifayyyjcbeumisvneiok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmYXl5eWpjYmV1bWlzdm5laW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MjU0ODAsImV4cCI6MjA1MDAwMTQ4MH0.9gNMnnkgfA4ECVasxW_BzDwiSsvSdhGvAc-xFaE-J1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  },
  global: {
    headers: {
      'Content-Type': 'application/json'
    }
  }
});